### ISSUE TITLE
Wrong number of arguments (request is nil with ActionController::Live)

### ISSUE THREAD

**Issue by fazo96** [julienbourdeau/debugbar#13]
I am getting this error when I enable debugbar 0.1.4 - I ran into #7 first, but updating to 0.1.4 fixed it

It seems very weird but I am not sure what it could be. What is weird about this setup is that this controller action relies on ActionController::Live and has this block at the end:

```ruby
ensure
  response.stream.close
end
```

I guess it might not work with debugbar

Here's the stack trace:

```
Puma caught this error: wrong number of arguments (given 0, expected 1) (ArgumentError)
/usr/local/rvm/gems/ruby-3.2.2/gems/debugbar-0.1.4/lib/debugbar/request.rb:78:in `method'
/usr/local/rvm/gems/ruby-3.2.2/gems/debugbar-0.1.4/lib/debugbar/request.rb:78:in `request_hash'
/usr/local/rvm/gems/ruby-3.2.2/gems/debugbar-0.1.4/lib/debugbar/request.rb:59:in `to_h'
/usr/local/rvm/gems/ruby-3.2.2/gems/debugbar-0.1.4/lib/debugbar/middlewares/track_current_request.rb:26:in `map'
/usr/local/rvm/gems/ruby-3.2.2/gems/debugbar-0.1.4/lib/debugbar/middlewares/track_current_request.rb:26:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/actionpack-7.1.2/lib/action_dispatch/middleware/request_id.rb:28:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/actionpack-7.1.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/actionpack-7.1.2/lib/action_dispatch/middleware/static.rb:25:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/actionpack-7.1.2/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/railties-7.1.2/lib/rails/engine.rb:529:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'
/usr/local/rvm/gems/ruby-3.2.2/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

I tried using `byebug` to run `request.method` and it works fine (returns `"POST"`) so I am not sure why it is crashing like that!

**Comment by julienbourdeau** [comment]
The error is misleading because NilClass has a `method` method. The real error is that request is `nil`.

I have never used `ActionController::Live`, I'll look into it. I'm thinking it may do some sort of "sub request" and the debugger doesn't support it (yet!).

The more info about your controller you can share, the better for me 🙏

**Comment by julienbourdeau** [comment]
I believe version 0.2.0 should fix the issue with ActiveController::Live. Can you try it and let me know?

**Comment by fazo96** [comment]
Hi, thanks for fixing it. 0.2.1 doesn't have this problem

**Comment by julienbourdeau** [comment]
Excellent news!
