### ISSUE TITLE
Puma caught this error: undefined method `body' for Rack::Files::Iterator

### ISSUE THREAD

**Issue by raihanM99** [julienbourdeau/debugbar#21]
In my Rails project, I encountered an issue related to handling attachments. Specifically, when accessing a page that invokes an attachment from Active Storage using (e.g `<%= user.avatar %>`), an error occurred.
```ruby
Puma caught this error: undefined method `body' for #<Rack::Files::Iterator:0x00007a6444b5d0b0 @path="/app/storage/up/0j/up0jdccu1cxhetiqc4esuczuufde", @ranges=[0..13031], @options={:mime_type=>"text/plain", :size=>13032}>

      @stream.body
             ^^^^^ (NoMethodError)
/gems/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/http/response.rb:305:in `body'
/gems/ruby/3.1.0/gems/debugbar-0.2.2/lib/debugbar/request.rb:94:in `response_hash'
/gems/ruby/3.1.0/gems/debugbar-0.2.2/lib/debugbar/request.rb:60:in `to_h'
.
.
.
``` 

This issue arose due to Rails generating a URL every time it accesses the Active Storage attachment.
```ruby
"GET /uploads/disk/active_storage_long_key/avatar1.jpg"
``` 

To resolve this, I modified the configuration in the `config/initializers/debugbar.rb` file to ignore `/uploads`, which successfully resolved the issue
```ruby
Debugbar.configure do |config|
  config.ignore_request = -> (env) { env['PATH_INFO'].start_with? '/uploads' }
end
```

**Comment by n1xn** [comment]
@raihanM99 thank you!

**Comment by gtrias** [comment]
Hello! I'm having the same problem but this workaround doesn't fit very well into our system since we get this errors from a GraphQL endpoint on which you would need to introspect the query to know if it's dealing with files.

It's also a pity not being able to see requests involving files in debugbar. 
Would it be possible to use another mechanism to generate `response_hash` here? https://github.com/julienbourdeau/debugbar/blob/master/lib/debugbar/request.rb#L94 Why it needs to use `response.body` for it?

I would be happy to contribute if you guide me on how to do so :)

**Comment by manuelmeurer** [comment]
Having this problem as well and had to deactivate debugbar because of it.

<img width="1711" alt="Image" src="https://github.com/user-attachments/assets/5f09dbf2-3216-4e39-a98f-6d9ec579cf70" />
